from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1227, 626)
        MainWindow.setMinimumSize(QtCore.QSize(600, 600))
        MainWindow.setStyleSheet("background-color:rgb(153, 204, 255)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.main_left_widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_left_widget.sizePolicy().hasHeightForWidth())
        self.main_left_widget.setSizePolicy(sizePolicy)
        self.main_left_widget.setStyleSheet("background-color:rgb(153, 204, 255)")
        self.main_left_widget.setObjectName("main_left_widget")
        self.gridLayout = QtWidgets.QGridLayout(self.main_left_widget)
        self.gridLayout.setObjectName("gridLayout")
        self.logout_button = QtWidgets.QPushButton(self.main_left_widget)
        self.logout_button.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.logout_button.setObjectName("logout_button")
        self.gridLayout.addWidget(self.logout_button, 5, 4, 1, 1)
        self.settings_button = QtWidgets.QPushButton(self.main_left_widget)
        self.settings_button.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.settings_button.setObjectName("settings_button")
        self.gridLayout.addWidget(self.settings_button, 5, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 5)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem1, 4, 0, 1, 5)
        self.night_mode_button = QtWidgets.QPushButton(self.main_left_widget)
        self.night_mode_button.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.night_mode_button.setObjectName("night_mode_button")
        self.gridLayout.addWidget(self.night_mode_button, 5, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 5, 3, 1, 1)
        self.acc_info_frame = QtWidgets.QFrame(self.main_left_widget)
        self.acc_info_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.acc_info_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.acc_info_frame.setObjectName("acc_info_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.acc_info_frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.acc_info_button = QtWidgets.QPushButton(self.acc_info_frame)
        self.acc_info_button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.acc_info_button.sizePolicy().hasHeightForWidth())
        self.acc_info_button.setSizePolicy(sizePolicy)
        self.acc_info_button.setMaximumSize(QtCore.QSize(16777215, 200))
        self.acc_info_button.setSizeIncrement(QtCore.QSize(0, 0))
        self.acc_info_button.setStyleSheet("border-image: url(C:/Users/Qjuchi/Desktop/Project_demo/user2.png)")
        self.acc_info_button.setText("")
        self.acc_info_button.setObjectName("acc_info_button")
        self.horizontalLayout_2.addWidget(self.acc_info_button)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.gridLayout.addWidget(self.acc_info_frame, 1, 0, 1, 5)
        self.widget = QtWidgets.QWidget(self.main_left_widget)
        self.widget.setStyleSheet("background-color:rgb(153, 204, 255)")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_left_sales = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Perpetua")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.main_left_sales.setFont(font)
        self.main_left_sales.setStyleSheet("")
        self.main_left_sales.setObjectName("main_left_sales")
        self.verticalLayout.addWidget(self.main_left_sales)
        self.main_left_purchase = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Perpetua")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.main_left_purchase.setFont(font)
        self.main_left_purchase.setObjectName("main_left_purchase")
        self.verticalLayout.addWidget(self.main_left_purchase)
        self.main_left_stats = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Perpetua")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.main_left_stats.setFont(font)
        self.main_left_stats.setObjectName("main_left_stats")
        self.verticalLayout.addWidget(self.main_left_stats)
        self.gridLayout.addWidget(self.widget, 3, 0, 1, 5)
        spacerItem5 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem5, 0, 1, 1, 3)
        self.horizontalLayout.addWidget(self.main_left_widget)
        spacerItem6 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.main_right_widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.main_right_widget.sizePolicy().hasHeightForWidth())
        self.main_right_widget.setSizePolicy(sizePolicy)
        self.main_right_widget.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.main_right_widget.setObjectName("main_right_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.main_right_widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.hide_show_button = QtWidgets.QPushButton(self.main_right_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hide_show_button.sizePolicy().hasHeightForWidth())
        self.hide_show_button.setSizePolicy(sizePolicy)
        self.hide_show_button.setCheckable(True)
        self.hide_show_button.setObjectName("hide_show_button")
        self.verticalLayout_2.addWidget(self.hide_show_button)
        self.stats_summary_label = QtWidgets.QLabel(self.main_right_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stats_summary_label.sizePolicy().hasHeightForWidth())
        self.stats_summary_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Perpetua")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.stats_summary_label.setFont(font)
        self.stats_summary_label.setObjectName("stats_summary_label")
        self.verticalLayout_2.addWidget(self.stats_summary_label)
        self.stats_summary = QtWidgets.QWidget(self.main_right_widget)
        self.stats_summary.setStyleSheet("background-color:rgb(0, 0, 0)")
        self.stats_summary.setObjectName("stats_summary")
        self.verticalLayout_2.addWidget(self.stats_summary)
        spacerItem7 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem7)
        self.sales_purchases_frame = QtWidgets.QFrame(self.main_right_widget)
        self.sales_purchases_frame.setStyleSheet("")
        self.sales_purchases_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sales_purchases_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sales_purchases_frame.setObjectName("sales_purchases_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.sales_purchases_frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.small_sales_widget = QtWidgets.QWidget(self.sales_purchases_frame)
        self.small_sales_widget.setObjectName("small_sales_widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.small_sales_widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.last_invoice_button1 = QtWidgets.QPushButton(self.small_sales_widget)
        self.last_invoice_button1.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.last_invoice_button1.setObjectName("last_invoice_button1")
        self.gridLayout_2.addWidget(self.last_invoice_button1, 3, 2, 1, 1)
        self.sales_label1 = QtWidgets.QLabel(self.small_sales_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sales_label1.sizePolicy().hasHeightForWidth())
        self.sales_label1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Perpetua")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.sales_label1.setFont(font)
        self.sales_label1.setObjectName("sales_label1")
        self.gridLayout_2.addWidget(self.sales_label1, 0, 1, 1, 2)
        self.new_invoice_button1 = QtWidgets.QPushButton(self.small_sales_widget)
        self.new_invoice_button1.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.new_invoice_button1.setObjectName("new_invoice_button1")
        self.gridLayout_2.addWidget(self.new_invoice_button1, 3, 1, 1, 1)
        self.small_sales_display = QtWidgets.QWidget(self.small_sales_widget)
        self.small_sales_display.setStyleSheet("background-color:rgb(0, 0, 0)")
        self.small_sales_display.setObjectName("small_sales_display")
        self.gridLayout_2.addWidget(self.small_sales_display, 1, 1, 1, 2)
        spacerItem8 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_2.addItem(spacerItem8, 2, 1, 1, 2)
        self.horizontalLayout_3.addWidget(self.small_sales_widget)
        self.small_purchase_widget = QtWidgets.QWidget(self.sales_purchases_frame)
        self.small_purchase_widget.setObjectName("small_purchase_widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.small_purchase_widget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.small_purchases_display = QtWidgets.QWidget(self.small_purchase_widget)
        self.small_purchases_display.setStyleSheet("background-color:rgb(0, 0, 0)")
        self.small_purchases_display.setObjectName("small_purchases_display")
        self.gridLayout_3.addWidget(self.small_purchases_display, 1, 0, 1, 2)
        self.last_purchase_button1 = QtWidgets.QPushButton(self.small_purchase_widget)
        self.last_purchase_button1.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.last_purchase_button1.setObjectName("last_purchase_button1")
        self.gridLayout_3.addWidget(self.last_purchase_button1, 3, 1, 1, 1)
        self.new_purchase_button1 = QtWidgets.QPushButton(self.small_purchase_widget)
        self.new_purchase_button1.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.new_purchase_button1.setObjectName("new_purchase_button1")
        self.gridLayout_3.addWidget(self.new_purchase_button1, 3, 0, 1, 1)
        self.purchases_label1 = QtWidgets.QLabel(self.small_purchase_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.purchases_label1.sizePolicy().hasHeightForWidth())
        self.purchases_label1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Perpetua")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.purchases_label1.setFont(font)
        self.purchases_label1.setObjectName("purchases_label1")
        self.gridLayout_3.addWidget(self.purchases_label1, 0, 0, 1, 2)
        spacerItem9 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_3.addItem(spacerItem9, 2, 0, 1, 2)
        self.horizontalLayout_3.addWidget(self.small_purchase_widget)
        self.verticalLayout_2.addWidget(self.sales_purchases_frame)
        self.horizontalLayout.addWidget(self.main_right_widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.logout_button.setText(_translate("MainWindow", "Logout"))
        self.settings_button.setText(_translate("MainWindow", "Settings"))
        self.night_mode_button.setText(_translate("MainWindow", "Night Mode"))
        self.main_left_sales.setText(_translate("MainWindow", "Sales:"))
        self.main_left_purchase.setText(_translate("MainWindow", "Purchases:"))
        self.main_left_stats.setText(_translate("MainWindow", "Stats:"))
        self.hide_show_button.setText(_translate("MainWindow", "Hide/Show"))
        self.stats_summary_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Stats Summary</p></body></html>"))
        self.last_invoice_button1.setText(_translate("MainWindow", "Last Invoice"))
        self.sales_label1.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">Sales</span></p></body></html>"))
        self.new_invoice_button1.setText(_translate("MainWindow", "New Invoice"))
        self.last_purchase_button1.setText(_translate("MainWindow", "Last Purchase"))
        self.new_purchase_button1.setText(_translate("MainWindow", "New Purchase"))
        self.purchases_label1.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Purchases</p></body></html>"))


class First(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self):
        QtWidgets.QMainWindow.__init__(self)
        self=self.setupUi(self)
